-module(dgen_registry).
-behaviour(supervisor).

-define(DOCATTRS, ?OTP_RELEASE >= 27).

-if(?DOCATTRS).
-moduledoc """
OTP-compatible process registry implementing the `{via, dgen_registry, {RegistryName, LogicalName}}` contract.

Standard OTP processes (`gen_server`, `gen_statem`, `gen_event`, etc.) can be registered
and addressed by name across an Erlang cluster.

See `docs/dgen_registry_design.md` for the full design, guarantees, and non-goals;
section references (e.g. `§5.7`) in the registry modules point there.

This module implements the four-function contract required for OTP `via` tuples:

- `register_name/2` — consistent write through the leader
- `unregister_name/1` — consistent delete through the leader
- `whereis_name/1` — lock-free snapshot read from the local member's ETS table
- `send/2` — routes a message to a named process

## Name terms

Every `via` name is a two-tuple `{RegistryName, LogicalName}` where
`RegistryName` identifies which registry to use (the one started with
`start_link/2`), and `LogicalName` is any term meaningful to the
application (atom, binary, tuple, …).

## Example

```erlang
{ok, _} = dgen_registry:start_link(my_registry, Tenant),

%% Start a gen_server registered in the dgen registry
gen_server:start_link({via, dgen_registry, {my_registry, user_service}},
                      my_server, [], []),

%% Call it from anywhere on the cluster
gen_server:call({via, dgen_registry, {my_registry, user_service}}, ping).
```

## Process identity

Starting a registry creates zero atoms. `Name` is supplied by the caller and is
application-controlled, not generated by this module. The top-level supervisor and
the elector are never registered under a name — the supervisor is addressed by the
pid `start_link/2,3` returns, and the elector is discovered by the member at startup
(its `$ancestors` process-dictionary entry, then `supervisor:which_children/1`) and
thereafter held as a pid. Only the **member** is locally registered, under `Name`
itself — the same atom also names its ETS table (`names_table/1`); no additional
atom is derived from it. This matters for applications that start many independent
registries dynamically (e.g. one per tenant): atoms are never garbage-collected, so
deriving additional atoms per registry (as earlier versions of this module did)
would grow the atom table without bound. See §4.8 of the design doc.

## Consistency model

All writes (`register_name`, `unregister_name`) and consistent reads
(`whereis_name_consistent`) go through the elected leader member process.
The leader is the single writer for the name table.

`whereis_name/1` (used by the OTP via-tuple machinery) is a snapshot read
served lock-free from the local member's `protected` ETS table, in the calling
process — no member-mailbox hop, no network hop, no backend round-trip. The
table is kept in sync by one-way replication casts from the leader. There is
therefore a short window after registration where a remote node's
`whereis_name/1` may still return `undefined`; this is the same
eventual-consistency trade-off as `gproc` global mode.

## Leadership

The elected leader is the member process on the Erlang node that most
recently committed a backend transaction for the elector queue — i.e.,
whoever wins the backend consensus. When leadership changes, the new leader
gathers the freshest names map from every reachable member and broadcasts a
snapshot to all followers on assumption. No distributed lock is used: the
leader-key commit fences the old leader, making the handoff window naturally
quiescent (§5.7 of the design doc).

## Auto-unregistration

The leader monitors every registered Pid. When a monitored process exits,
the leader removes the entry and propagates `{name_unregistered}` to all
follower members.

## Metadata and queries

A registration can carry metadata for its lifetime: `register_name/3` /
`set_metadata/2` attach an `index` map (queryable) and an opaque `data` payload;
`get_metadata/1` / `get_metadata_consistent/1` read it back (lock-free / leader-routed,
mirroring `whereis_name/1` / `whereis_name_consistent/1`). `query/2` /
`query_consistent/2` find every registration whose `index` satisfies a conjunction of
exact equalities. See §4.7 of the design doc.
""".
-endif.

-export([
    %% Supervisor start
    start_link/2,
    start_link/3,
    %% OTP via-tuple registry contract
    register_name/2,
    unregister_name/1,
    whereis_name/1,
    send/2,
    %% Registration metadata
    register_name/3,
    set_metadata/2,
    get_metadata/1,
    get_metadata_consistent/1,
    %% Indexed metadata queries
    query/2,
    query_consistent/2,
    %% Consistent (leader-routed) name lookup
    whereis_name_consistent/1,
    %% Convenience queries
    get_leader/1,
    get_members/1,
    get_epoch/1,
    %% Readiness
    ready/1,
    await_ready/1,
    await_ready/2,
    %% Process identity helpers (exported for tests / introspection)
    member_name/1,
    names_table/1,
    elector_pid/1
]).

-export([init/1]).

-export_type([member_id/0, registry_opts/0]).

%% A member identifier is the pair of the Erlang node and the registry name.
-type member_id() :: {node(), atom()}.

%% Per-registry tuning options passed to `start_link/3`.
-type registry_opts() :: #{atom() => term()}.

%% ---------------------------------------------------------------------------
%% Supervisor start
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Starts the registry `Name` with default options. See `start_link/3` for per-registry tuning.".
-endif.
-spec start_link(Name :: atom(), Tenant :: dgen_backend:tenant()) ->
    supervisor:startlink_ret().
start_link(Name, Tenant) ->
    start_link(Name, Tenant, #{}).

-if(?DOCATTRS).
-doc """
Starts the registry `Name` with per-registry options `Opts`.

`Opts` is a map of tuning knobs scoped to *this* registry — `register_replicas`,
`replicate_timeout`, `strict_replication`, `terminate_on_conflict`,
`conflict_kill_budget`, `reject_when_degraded`. Each unset key falls back to the
`dgen` application environment, then to a built-in default, so different registries
can be tuned independently. See `docs/dgen_registry_design.md` (§8 Configuration).

The supervisor itself is **not** registered under a name — hold onto the `pid()`
this returns (e.g. `Supervisor.stop/2` to tear it down) rather than looking it up
later by `Name`, which now names the member, not the supervisor. See the
"Process identity" note above.
""".
-endif.
-spec start_link(Name :: atom(), Tenant :: dgen_backend:tenant(), Opts :: registry_opts()) ->
    supervisor:startlink_ret().
start_link(Name, Tenant, Opts) ->
    supervisor:start_link(?MODULE, {Name, Tenant, Opts}).

%% ---------------------------------------------------------------------------
%% OTP via-tuple registry contract
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Registers `Pid` under `{RegistryName, LogicalName}`.

Routes through the local member, which forwards to the leader if needed.
Returns `yes` on success, `no` if the name is already taken or no leader
is currently elected.
""".
-endif.
-spec register_name({atom(), term()}, pid()) -> yes | no.
register_name(Name, Pid) ->
    register_name(Name, Pid, #{}).

-if(?DOCATTRS).
-doc """
Removes the registration for `{RegistryName, LogicalName}`.

Fire-and-forget: routes through the local member, which forwards to the
leader. The local member also removes the entry from its own map
immediately so snapshot reads on this node are consistent right away.
""".
-endif.
-spec unregister_name({atom(), term()}) -> ok.
unregister_name({RegistryName, LogicalName}) ->
    gen_server:cast(member_name(RegistryName), {unregister, LogicalName}).

-if(?DOCATTRS).
-doc """
Snapshot read — served lock-free from the local member's ETS table.

Runs entirely in the **calling process** (an `ets:lookup/2` against the member's
`protected` names table), so it never blocks on the member's mailbox, the leader,
or the backend — many callers read concurrently. May be slightly stale on follower
nodes in the brief window between a remote registration and the replication cast
arriving, and returns `undefined` while the member is (re)starting and its table
does not yet exist.
""".
-endif.
-spec whereis_name({atom(), term()}) -> pid() | undefined.
whereis_name({RegistryName, LogicalName}) ->
    try ets:lookup(names_table(RegistryName), LogicalName) of
        [{_Name, Pid, _Index, _Data} | _] -> Pid;
        [] -> undefined
    catch
        %% The table does not exist yet (member starting / restarting after a
        %% crash) — treat as not-registered rather than crashing the caller.
        error:badarg -> undefined
    end.

-if(?DOCATTRS).
-doc """
Sends `Msg` to the process registered as `Name`, returning the Pid.

Exits with reason `{badarg, {Name, Msg}}` if the name is not registered.
Called internally by gen_server/gen_event for `{via, …}` routing.
""".
-endif.
-spec send({atom(), term()}, term()) -> pid().
send(Name, Msg) ->
    case whereis_name(Name) of
        undefined ->
            exit({badarg, {Name, Msg}});
        Pid ->
            Pid ! Msg,
            Pid
    end.

%% ---------------------------------------------------------------------------
%% Registration metadata
%% ---------------------------------------------------------------------------
%% Metadata is attached to a registration (keyed by name) and lives exactly as long as
%% the registration does — it is removed automatically when the process exits or is
%% unregistered. A `MetaSpec` is `#{index => #{attr() => value()}, data => term()}`
%% (both optional): `index` is the queryable metadata, `data` an opaque payload returned
%% verbatim. See §4.7 of the design doc.

-if(?DOCATTRS).
-doc """
Registers `Pid` under `{RegistryName, LogicalName}` with metadata, in one fenced step.

`MetaSpec` is `#{index => map(), data => term()}` (both optional; defaults `#{}` and
`undefined`). Like `register_name/2`, returns `yes` on success or `no` if the name is
already taken, no leader is currently elected, or the leader could not be reached in
time — registration always returns a verdict rather than exiting on a routing
timeout (a caller that hears `no` retries; it never has to handle a timeout exit).
""".
-endif.
-spec register_name({atom(), term()}, pid(), map()) -> yes | no.
register_name({RegistryName, LogicalName}, Pid, MetaSpec) ->
    try
        gen_server:call(member_name(RegistryName), {register, LogicalName, Pid, meta_of(MetaSpec)})
    catch
        %% The member (or the leader behind it) did not answer in time — e.g. the
        %% leader became unreachable after the forward was sent.  The contract is a
        %% verdict, not an exit: answer `no` so the caller retries.  A missing
        %% registry (noproc) still exits — that is a usage error, not a timeout.
        exit:{timeout, _} -> no
    end.

-if(?DOCATTRS).
-doc """
Replaces the metadata of the existing registration `{RegistryName, LogicalName}`.

`MetaSpec` is `#{index => map(), data => term()}` (both optional; an omitted field
becomes `#{}` / `undefined` — this is a replace, not a merge). Routes through the leader
and rides the fenced commit. Returns `ok`, `{error, not_registered}` if the name is not
currently bound, or `{error, no_leader}` if no leader is elected (or leadership changed
mid-flight — retry).
""".
-endif.
-spec set_metadata({atom(), term()}, map()) -> ok | {error, not_registered | no_leader}.
set_metadata({RegistryName, LogicalName}, MetaSpec) ->
    {Index, Data} = meta_of(MetaSpec),
    try
        gen_server:call(member_name(RegistryName), {set_metadata, LogicalName, Index, Data})
    catch
        exit:_ -> {error, no_leader}
    end.

-if(?DOCATTRS).
-doc """
Snapshot read of a registration's metadata — served lock-free from the calling process.

Like `whereis_name/1`, this is an `ets:lookup/2` against the local member's `protected`
table with no member round-trip. Returns `{ok, #{pid := pid(), index := map(), data :=
term()}}` for a registered name, or `undefined` if it is not registered (or the member's
table does not exist yet). May lag a recent change made on another node.
""".
-endif.
-spec get_metadata({atom(), term()}) ->
    {ok, #{pid := pid(), index := map(), data := term()}} | undefined.
get_metadata({RegistryName, LogicalName}) ->
    try ets:lookup(names_table(RegistryName), LogicalName) of
        [{_Name, Pid, Index, Data} | _] -> {ok, #{pid => Pid, index => Index, data => Data}};
        [] -> undefined
    catch
        error:badarg -> undefined
    end.

-if(?DOCATTRS).
-doc """
Consistent metadata read routed through the leader (authoritative, never stale).

Returns the same shape as `get_metadata/1`. More expensive (one network hop) but
reflects the leader's committed view.
""".
-endif.
-spec get_metadata_consistent({atom(), term()}) ->
    {ok, #{pid := pid(), index := map(), data := term()}} | undefined.
get_metadata_consistent({RegistryName, LogicalName}) ->
    try
        gen_server:call(member_name(RegistryName), {get_metadata, LogicalName})
    catch
        exit:_ -> undefined
    end.

-if(?DOCATTRS).
-doc """
Finds every registration whose indexed metadata satisfies *all* of `Constraints`.

`Constraints` is `#{attr() => value()}` — a conjunction of exact equalities (AND-equal)
matched against each registration's `index` map. Returns a point-in-time list of
`#{name, pid, index, data}` matches (possibly empty), or `{error, empty_query}` if
`Constraints` is empty (use a future `list/1` for "everything").

This is a **batch-consistent snapshot** read of the local member's replica: it runs on
the member's mailbox (unlike the lock-free single-key reads) so it never observes a
half-applied group commit, but it may still lag a change made on another node. A
returned pid may already have died — treat results as candidates, not liveness
guarantees.
""".
-endif.
-spec query(atom(), map()) ->
    [#{name := term(), pid := pid(), index := map(), data := term()}] | {error, empty_query}.
query(_RegistryName, Constraints) when map_size(Constraints) =:= 0 ->
    {error, empty_query};
query(RegistryName, Constraints) ->
    try
        gen_server:call(member_name(RegistryName), {query, Constraints})
    catch
        exit:_ -> []
    end.

-if(?DOCATTRS).
-doc """
Like `query/2`, but routed through the leader for an authoritative (never-stale) result.

Returns the same shape as `query/2`. More expensive (it serialises on the leader's
mailbox, one network hop from a follower) but reflects the leader's committed view.
""".
-endif.
-spec query_consistent(atom(), map()) ->
    [#{name := term(), pid := pid(), index := map(), data := term()}] | {error, empty_query}.
query_consistent(_RegistryName, Constraints) when map_size(Constraints) =:= 0 ->
    {error, empty_query};
query_consistent(RegistryName, Constraints) ->
    try
        gen_server:call(member_name(RegistryName), {query_consistent, Constraints})
    catch
        exit:_ -> []
    end.

%% Parse a public MetaSpec (`#{index => …, data => …}`, both optional) into the internal
%% `{Index, Data}` pair, defaulting to the empty metadata.
-spec meta_of(map()) -> {map(), term()}.
meta_of(MetaSpec) ->
    {maps:get(index, MetaSpec, #{}), maps:get(data, MetaSpec, undefined)}.

%% ---------------------------------------------------------------------------
%% Consistent name lookup (leader-routed)
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Consistent read routed through the leader.

Returns the authoritative Pid for `LogicalName`, or `undefined` if not
registered. More expensive than `whereis_name/1` but never stale.
""".
-endif.
-spec whereis_name_consistent({atom(), term()}) -> pid() | undefined.
whereis_name_consistent({RegistryName, LogicalName}) ->
    try
        gen_server:call(member_name(RegistryName), {whereis, LogicalName})
    catch
        exit:_ -> undefined
    end.

%% ---------------------------------------------------------------------------
%% Convenience queries (bypass durable queue, always fresh)
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Returns the current leader member id, or `undefined` if no leader is elected.".
-endif.
-spec get_leader(Name :: atom()) -> member_id() | undefined.
get_leader(Name) ->
    with_elector(Name, undefined, fun(Pid) -> dgen_server:priority_call(Pid, get_leader) end).

-if(?DOCATTRS).
-doc "Returns the current leader epoch. Increments each time a new leader is elected.".
-endif.
-spec get_epoch(Name :: atom()) -> non_neg_integer().
get_epoch(Name) ->
    with_elector(Name, 0, fun(Pid) -> dgen_server:priority_call(Pid, get_epoch) end).

%% Poll interval and per-probe call bound for await_ready/2.
-define(READY_POLL_INTERVAL, 50).
-define(READY_CALL_TIMEOUT, 1000).

-if(?DOCATTRS).
-doc """
Is the registry on this node ready to serve registrations *right now*?

Returns `true` once the local member both knows a leader and has synced registry
state (applied the leader's snapshot, or assumed leadership itself). Returns `false`
while it is still starting/joining, has no elected leader, or is momentarily
unresponsive (a busy member is treated as not-ready rather than blocking the caller).

This is a point-in-time check; use `await_ready/2` to block until ready. Note that
readiness means registrations are being *served*, not that any particular
registration will return `yes` (a name may already be taken, or leadership may move).
""".
-endif.
-spec ready(Name :: atom()) -> boolean().
ready(Name) ->
    try gen_server:call(member_name(Name), ready, ?READY_CALL_TIMEOUT) of
        Ready when is_boolean(Ready) -> Ready;
        _ -> false
    catch
        %% Member starting/restarting (noproc), or busy past the probe bound
        %% (timeout) — not ready yet.
        exit:_ -> false
    end.

-if(?DOCATTRS).
-doc "Blocks until `ready/1` holds, or 5s elapses. See `await_ready/2`.".
-endif.
-spec await_ready(Name :: atom()) -> ok | {error, timeout}.
await_ready(Name) ->
    await_ready(Name, 5000).

-if(?DOCATTRS).
-doc """
Blocks until the registry on this node is ready to serve registrations, or `Timeout`
(milliseconds) elapses.

Returns `ok` once `ready/1` holds, or `{error, timeout}` if the deadline passes first.
Intended for a node that has just started/joined a cluster: it waits out leader
election and the join handoff (the leader gathers and delivers the names snapshot)
before the caller starts registering, so registrations are not fast-rejected against a
not-yet-known leader. Safe to call from many nodes; it only reads local member state.
""".
-endif.
-spec await_ready(Name :: atom(), Timeout :: non_neg_integer()) -> ok | {error, timeout}.
await_ready(Name, Timeout) ->
    Deadline = erlang:monotonic_time(millisecond) + Timeout,
    await_ready_loop(Name, Deadline).

await_ready_loop(Name, Deadline) ->
    case ready(Name) of
        true ->
            ok;
        false ->
            case erlang:monotonic_time(millisecond) < Deadline of
                true ->
                    timer:sleep(?READY_POLL_INTERVAL),
                    await_ready_loop(Name, Deadline);
                false ->
                    {error, timeout}
            end
    end.

-if(?DOCATTRS).
-doc "Returns the list of all current member ids in the registry.".
-endif.
-spec get_members(Name :: atom()) -> [member_id()].
get_members(Name) ->
    with_elector(Name, [], fun(Pid) -> dgen_server:priority_call(Pid, get_members) end).

%% Resolve the elector via `elector_pid/1` and apply `Fun` to it, or return `Default`
%% if the member (and so the elector) cannot currently be found — the registry may not
%% have started yet, or may be mid-restart. Keeps get_leader/get_epoch/get_members
%% bypassing the member's mailbox entirely, as before (§8): only an elector lookup is
%% added, not a member round-trip.
with_elector(Name, Default, Fun) ->
    case elector_pid(Name) of
        undefined -> Default;
        Pid -> Fun(Pid)
    end.

%% ---------------------------------------------------------------------------
%% Process identity helpers
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Returns the registered name of the member process for the given registry name.

Identity today (`member_name(Name) =:= Name`) — the member is registered under
`Name` directly. Kept as a function (rather than inlining `Name` at call sites) so
callers do not depend on that being the case.
""".
-endif.
-spec member_name(atom()) -> atom().
member_name(Name) ->
    Name.

-if(?DOCATTRS).
-doc """
Returns the ETS table name holding the registry's local `Name => Pid` replica.

Identity today (`names_table(Name) =:= Name`) — the member's names table is
named `Name` directly (ETS `named_table` names and Erlang process-registration
names are separate namespaces, so this does not collide with the member's own
registration). The table is owned and written by the member (a `protected`,
`read_concurrency` table) and read lock-free from any process — see
`whereis_name/1`.
""".
-endif.
-spec names_table(atom()) -> atom().
names_table(Name) ->
    Name.

-if(?DOCATTRS).
-doc """
Returns the current elector `pid()` for registry `Name`, or `undefined` if the
member (and so the elector) cannot currently be found.

The elector has no registered name — it is discovered by locating the member
(registered as `Name`), reading its `$ancestors` process-dictionary entry (set by
`proc_lib` at spawn time) to find the shared supervisor, then reading that
supervisor's children (`supervisor:which_children/1`) for the one with child id
`elector`. This is an all-local, in-memory operation (no network hop); it is what
`get_leader/1`, `get_epoch/1`, and `get_members/1` use internally, and is exported
for introspection.
""".
-endif.
-spec elector_pid(atom()) -> pid() | undefined.
elector_pid(Name) ->
    case whereis(Name) of
        undefined ->
            undefined;
        MemberPid ->
            case ancestors_of(MemberPid) of
                [Sup | _] ->
                    case lists:keyfind(elector, 1, supervisor:which_children(Sup)) of
                        {elector, ElectorPid, _Type, _Modules} when is_pid(ElectorPid) ->
                            ElectorPid;
                        _ ->
                            undefined
                    end;
                [] ->
                    undefined
            end
    end.

%% Reads Pid's `$ancestors` process-dictionary entry: the list of supervisor/starter
%% identifiers `proc_lib` records for a process at spawn time, immediate parent
%% first. There is no public `proc_lib` accessor for this (it is conventionally read
%% straight out of the dictionary — the same technique tools like `recon` use); each
%% entry is a pid, or a registered name if that ancestor had one, either of which
%% `supervisor:which_children/1` accepts directly.
-spec ancestors_of(pid()) -> [pid() | atom()].
ancestors_of(Pid) ->
    case erlang:process_info(Pid, dictionary) of
        {dictionary, Dict} -> proplists:get_value('$ancestors', Dict, []);
        undefined -> []
    end.

%% ---------------------------------------------------------------------------
%% Supervisor callbacks
%% ---------------------------------------------------------------------------

init({Name, Tenant, Opts}) ->
    %% Elector must start first: the member discovers it (via this supervisor,
    %% see dgen_registry_member's `discover_elector` handle_continue) and casts
    %% `{join, MemberId}` to it right after. A large consume_k is chosen because the
    %% in-transaction work is very small, and we want to keep a single node as the
    %% sole consumer as much as possible, to avoid leadership churn. consume_k > 1
    %% also disables dgen_server inlining, so every elector call rides the batched
    %% consume loop rather than being served ad hoc on the receiving node — keeping
    %% the consumer (hence the leader) stable.
    %%
    %% The elector is deliberately unnamed (`dgen_server:start_link/3`, no `Reg`):
    %% it has no registered name at all, local or otherwise. The member finds it by
    %% pid via this supervisor instead — see the "Process identity" moduledoc note.
    ElectorSpec = #{
        id => elector,
        start =>
            {dgen_server, start_link, [
                dgen_registry_elector,
                #{name => Name},
                [{tenant, Tenant}, {consume_k, 50}]
            ]},
        restart => permanent,
        shutdown => 5000,
        type => worker,
        modules => [dgen_server, dgen_registry_elector]
    },

    %% Tuid matches the elector's (see dgen_registry_elector:init/1) so the member
    %% can compute the leader key and the per-registry version key directly.
    Tuid = {<<"dgen_registry.">>, atom_to_binary(Name)},
    MemberSpec = #{
        id => member,
        start =>
            {dgen_registry_member, start_link, [
                Name,
                #{
                    name => Name,
                    tenant => Tenant,
                    tuid => Tuid,
                    config => Opts
                }
            ]},
        restart => permanent,
        shutdown => 5000,
        type => worker,
        modules => [dgen_registry_member]
    },

    %% one_for_all: the elector and member are one unit (the member holds a pid
    %% reference to the elector, discovered once at startup — see the moduledoc's
    %% "Process identity" note). If either crashes, restart both together so the
    %% member never runs with a stale elector reference; there is no cross-restart
    %% pid-staleness case to handle at the application level.
    {ok, {#{strategy => one_for_all, intensity => 5, period => 10}, [ElectorSpec, MemberSpec]}}.
