-module(dgen_registry).
-behaviour(supervisor).

-define(DOCATTRS, ?OTP_RELEASE >= 27).

%% The transform, for a module that is mostly a supervisor and an API surface.
%%
%% What matters is *where this code runs*.  `register_name/2`, `unregister_name/1`,
%% `whereis_name/1`, `query/2` and the rest execute in the **caller's** process, and
%% under simulation the caller is a process the scheduler owns.  So every
%% `gen_server:call/2,3` here has to be the one `eta_net` provides rather than
%% OTP's -- not for the fault injection, but for the clock and the schedule.
%%
%% Left untransformed, such a call goes into `gen:do_call/4`, which is OTP code no
%% transform reaches, and takes two real-time dependencies with it: a
%% `receive ... after Timeout` on the wall clock, and a real `erlang:monitor` whose
%% `DOWN` the VM delivers when it likes rather than when the schedule says.  Both
%% put a scheduled process's progress outside the schedule, and neither shows up in
%% `eta_run:audit/1` -- the run simply stops being a function of its seed.  Found
%% exactly that way: clients parked in `gen:do_call/4` at the step where two runs
%% of one seed first disagreed.
-include("../include/dgen_eta.hrl").

%% Supervisor flags that exist only to keep this tree schedulable under simulation.
%%
%% The simulation declares these supervisors to `eta_sched` — it has to, because
%% `elector_pid/1` below asks a supervisor for its children, so every
%% `get_leader/1`, `get_epoch/1` and `get_members/1` is a call into one. A process
%% the scheduler owns must have no real timers, and on OTP 28 a supervisor does:
%% `hibernate_after` arrived with a 1000ms default, implemented as a `gen_server`
%% timeout, and `supervisor` is OTP code no parse transform reaches. So every
%% supervisor armed a wall-clock timer that dropped a message into a scheduled
%% process's mailbox whenever real time said so. It moved with machine load — six
%% simulation suites running at once made it fail about one run in three, while
%% one at a time looked clean — and it was the last thing keeping `mix dst` from
%% being a function of its seed.
%%
%% Guarded twice over, so a release build is byte-for-byte what it was: `DST` is
%% set only by the test profile, and the key does not exist before OTP 28.
-ifdef(DST).
-if(?OTP_RELEASE >= 28).
-define(SUP_SIM_FLAGS, #{hibernate_after => infinity}).
-else.
-define(SUP_SIM_FLAGS, #{}).
-endif.
-else.
-define(SUP_SIM_FLAGS, #{}).
-endif.

-if(?DOCATTRS).
-moduledoc """
OTP-compatible process registry implementing the `{via, dgen_registry, {RegistryName, LogicalName}}` contract.

Standard OTP processes (`gen_server`, `gen_statem`, `gen_event`, etc.) can be registered
and addressed by name across an Erlang cluster.

See `docs/dgen_registry_design.md` for the full design, guarantees, and non-goals;
section references (e.g. `§5.7`) in the registry modules point there.

This module implements the four-function contract required for OTP `via` tuples:

- `register_name/2` — consistent write through the leader
- `unregister_name/1` — consistent delete through the leader
- `whereis_name/1` — lock-free snapshot read from the local member's ETS table
- `send/2` — routes a message to a named process

## Name terms

Every `via` name is a two-tuple `{RegistryName, LogicalName}` where
`RegistryName` identifies which registry to use (the one started with
`start_link/2`), and `LogicalName` is any term meaningful to the
application (atom, binary, tuple, …).

## Example

```erlang
{ok, _} = dgen_registry:start_link(my_registry, Tenant),

%% Start a gen_server registered in the dgen registry
gen_server:start_link({via, dgen_registry, {my_registry, user_service}},
                      my_server, [], []),

%% Call it from anywhere on the cluster
gen_server:call({via, dgen_registry, {my_registry, user_service}}, ping).
```

## Process identity

Starting a registry creates zero atoms. `Name` is supplied by the caller and is
application-controlled, not generated by this module. The top-level supervisor, the
elector, and the connector are never registered under a name — the supervisor is
addressed by the pid `start_link/2,3` returns, and the elector is discovered at
startup (its `$ancestors` process-dictionary entry, then
`supervisor:which_children/1`) and thereafter held as a pid by the member and the
connector. Only the **member** is locally registered, under `Name` itself — the same
atom also names its ETS table (`names_table/1`); no additional atom is derived from
it. This matters for applications that start many independent registries dynamically
(e.g. one per tenant): atoms are never garbage-collected, so deriving additional
atoms per registry (as earlier versions of this module did) would grow the atom table
without bound. See §4.8 of the design doc.

## Consistency model

All writes (`register_name`, `unregister_name`) and consistent reads
(`whereis_name_consistent`) go through the elected leader member process.
The leader is the single writer for the name table.

`whereis_name/1` (used by the OTP via-tuple machinery) is a snapshot read
served lock-free from the local member's `protected` ETS table, in the calling
process — no member-mailbox hop, no network hop, no backend round-trip. The
table is kept in sync by one-way replication casts from the leader. There is
therefore a short window after registration where a remote node's
`whereis_name/1` may still return `undefined`; this is the same
eventual-consistency trade-off as `gproc` global mode.

## Leadership

The elected leader is the member process on the Erlang node that most
recently committed a backend transaction for the elector queue — i.e.,
whoever wins the backend consensus. When leadership changes, the new leader
gathers the freshest names map from every reachable member and broadcasts a
snapshot to all followers on assumption. No distributed lock is used: the
leader-key commit fences the old leader, making the handoff window naturally
quiescent (§5.7 of the design doc).

## Auto-unregistration

The leader monitors every registered Pid. When a monitored process exits,
the leader removes the entry and propagates `{name_unregistered}` to all
follower members.

## Metadata and queries

A registration can carry metadata for its lifetime: `register_name/3` /
`set_metadata/2` attach an `index` map (queryable) and an opaque `data` payload;
`get_metadata/1` / `get_metadata_consistent/1` read it back (lock-free / leader-routed,
mirroring `whereis_name/1` / `whereis_name_consistent/1`). `query/2` /
`query_consistent/2` find every registration whose `index` satisfies a conjunction of
exact equalities. See §4.7 of the design doc.

## Presence

`subscribe/4` / `unsubscribe/2` turn a query into a live feed: a subscription watches
one query and notifies (via a second query) whenever the set of processes matching the
watched query changes — `{dgen_presence, SubId, [{joined | left, Name, Pid}]}`.
Subscriptions are **durable** (stored in the elector's backend state, keyed by an
application id), so they outlive the cluster — built for process-presence systems whose
stakeholders are database entities. See §4.9 of the design doc.

*This documentation is LLM-generated. See the AI disclosure in `README.md`.*
""".
-endif.

-export([
    %% Supervisor start
    start_link/2,
    start_link/3,
    %% OTP via-tuple registry contract
    register_name/2,
    unregister_name/1,
    whereis_name/1,
    send/2,
    %% Registration metadata
    register_name/3,
    set_metadata/2,
    get_metadata/1,
    get_metadata_consistent/1,
    %% Indexed metadata queries
    query/2,
    query_consistent/2,
    %% Presence: durable watch/notify subscriptions
    subscribe/4,
    unsubscribe/2,
    unsubscribe_all/1,
    subscriptions/1,
    %% Teardown / durable-state cleanup
    delete/2,
    %% Consistent (leader-routed) name lookup
    whereis_name_consistent/1,
    %% Convenience queries
    get_leader/1,
    get_members/1,
    get_epoch/1,
    %% Readiness and introspection
    ready/1,
    await_ready/1,
    await_ready/2,
    status/1,
    %% Process identity helpers (exported for tests / introspection)
    member_name/1,
    names_table/1,
    elector_pid/1
]).

-export([init/1]).

-export_type([member_id/0, registry_opts/0, query/0, presence_event/0]).

%% A member identifier is the pair of the Erlang node and the registry name.
-type member_id() :: {node(), atom()}.

%% Per-registry tuning options passed to `start_link/3`.
-type registry_opts() :: #{atom() => term()}.

%% A query over registrations' indexed metadata, used by the presence subscriptions
%% (`subscribe/4`).  Extensible by design — only the AND-equal form exists today:
%% `{all, #{attr() => value()}}` matches a registration whose `index` map contains
%% *all* of the given exact equalities (the same semantics as `query/2`).  A bare
%% constraints map is accepted anywhere a query is and is treated as `{all, Map}`.
%% Future query kinds (ranges, disjunction, …) slot in as new tagged variants without
%% changing existing call sites.
-type query() :: {'all', #{term() => term()}} | #{term() => term()}.

%% A presence change delivered to a subscription's notify targets: a name entered
%% (`joined`) or left (`left`) the watch query's result set.  See `subscribe/4`.
-type presence_event() :: {joined | left, Name :: term(), Pid :: pid()}.

%% ---------------------------------------------------------------------------
%% Supervisor start
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Starts the registry `Name` with default options. See `start_link/3` for per-registry tuning.".
-endif.
-spec start_link(Name :: atom(), Tenant :: dgen_backend:tenant()) ->
    supervisor:startlink_ret().
start_link(Name, Tenant) ->
    start_link(Name, Tenant, #{}).

-if(?DOCATTRS).
-doc """
Starts the registry `Name` with per-registry options `Opts`.

`Opts` is a map of tuning knobs scoped to *this* registry — `register_replicas`,
`replicate_timeout`, `strict_replication`, `terminate_on_conflict`,
`conflict_kill_budget`, `reject_when_degraded`, `connectivity`. Each unset key falls
back to the `dgen` application environment, then to a built-in default, so different
registries can be tuned independently. `connectivity => provided_externally` turns off
this registry's proactive distribution mesh so it free-rides on connections another
registry maintains (§4.6) — the rest default to a self-sufficient, single-fault-tolerant
registry. See `docs/dgen_registry_design.md` (§8 Configuration).

The supervisor itself is **not** registered under a name — hold onto the `pid()`
this returns (e.g. `Supervisor.stop/2` to tear it down) rather than looking it up
later by `Name`, which now names the member, not the supervisor. See the
"Process identity" note above.

## `keyspace` — separating identity from the coordination keyspace

`Name` normally plays three roles at once: this member's **identity** (the registered
process name, the ETS table name, and the second element of its `member_id/0`), and
the registry's **keyspace** (the tuid prefixing every durable key — the elector queue,
the leader key, the version key).

The optional `keyspace` option splits the second role out:

```erlang
dgen_registry:start_link(member_a, Tenant, #{keyspace => shared_registry}),
dgen_registry:start_link(member_b, Tenant, #{keyspace => shared_registry}).
```

Both members now coordinate through *one* registry's durable state — one elector
queue, one leader key, one version key — while keeping distinct identities, so they
elect a leader between themselves and replicate to each other exactly as members on
separate nodes do. It defaults to `Name`, which is the ordinary one-member-per-node
deployment.

This exists for **simulation**: `member_id/0` is `{node(), Name}`, so without it a
single VM can host at most one member of a given registry and any multi-member test
needs real distribution and real nodes. With it, an N-member cluster runs inside one
BEAM — which is what makes deterministic, seeded, replayable simulation of the
replication protocol possible (see `test/support/sim/`). It is **not** intended for
production deployment: two members of one registry sharing a VM share a fate, so they
are not two holders in the sense of Guarantee 4, and the connector's node-level
backstops (§4.6) cannot distinguish them.

Note that `delete/2` takes the **keyspace** name, not a member's `Name`.
""".
-endif.
-spec start_link(Name :: atom(), Tenant :: dgen_backend:tenant(), Opts :: registry_opts()) ->
    supervisor:startlink_ret().
start_link(Name, Tenant, Opts) ->
    supervisor:start_link(?MODULE, {Name, Tenant, Opts}).

%% ---------------------------------------------------------------------------
%% OTP via-tuple registry contract
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Registers `Pid` under `{RegistryName, LogicalName}`.

Routes through the local member, which forwards to the leader if needed.
Returns `yes` on success, `no` if the name is already held by a *different*
process or no leader is currently elected.

Registering the **same** pid under the **same** name again is an idempotent
`yes` (not a `no`): a caller whose register call timed out — but whose
registration in fact committed — can safely redrive it and get a decisive
`yes` for its own binding. See `register_name/3` for the timeout contract.
""".
-endif.
-spec register_name({atom(), term()}, pid()) -> yes | no.
register_name(Name, Pid) ->
    register_name(Name, Pid, #{}).

-if(?DOCATTRS).
-doc """
Removes the registration for `{RegistryName, LogicalName}`. Always returns `ok`.

Routes through the local member as a **call** (mirroring the register path): the
member removes the entry from its own replica immediately — snapshot reads on this
node see the delete at once — and forwards the removal to the leader as a *tracked*
request. `ok` normally means the leader has committed the removal; if the leader is
unreachable (or answers late), `ok` means the removal is **stashed and re-driven** —
forwarded to the current leader as a pid-guarded retract on the next leadership
change or rejoin snapshot — so an explicit unregister is never silently lost
(Non-goal 5 of the design doc). Cluster-wide visibility remains eventually
consistent (replication is asynchronous).
""".
-endif.
-spec unregister_name({atom(), term()}) -> ok.
unregister_name({RegistryName, LogicalName}) ->
    try
        gen_statem:call(
            member_name(RegistryName),
            {unregister, LogicalName},
            %% Same caller-side bound as the other leader-routed writes — see
            %% set_metadata/2.
            dgen_config:register_timeout(#{})
        )
    catch
        %% noproc: the registry is stopped/absent — nothing to unregister, `ok` is
        %% truthful.  timeout: the removal is already stashed on the member and will
        %% be re-driven; the public contract stays `ok` (the via machinery ignores
        %% the return value, and unlike register there is no wrong verdict to mask).
        exit:_ -> ok
    end.

-if(?DOCATTRS).
-doc """
Snapshot read — served lock-free from the local member's ETS table.

Runs entirely in the **calling process** (an `ets:lookup/2` against the member's
`protected` names table), so it never blocks on the member's mailbox, the leader,
or the backend — many callers read concurrently. May be slightly stale on follower
nodes in the brief window between a remote registration and the replication cast
arriving, and returns `undefined` while the member is (re)starting and its table
does not yet exist.
""".
-endif.
-spec whereis_name({atom(), term()}) -> pid() | undefined.
whereis_name({RegistryName, LogicalName}) ->
    try ets:lookup(names_table(RegistryName), LogicalName) of
        [{_Name, Pid, _Index, _Data} | _] -> Pid;
        [] -> undefined
    catch
        %% The table does not exist yet (member starting / restarting after a
        %% crash) — treat as not-registered rather than crashing the caller.
        error:badarg -> undefined
    end.

-if(?DOCATTRS).
-doc """
Sends `Msg` to the process registered as `Name`, returning the Pid.

Exits with reason `{badarg, {Name, Msg}}` if the name is not registered.
Called internally by gen_server/gen_event for `{via, …}` routing.
""".
-endif.
-spec send({atom(), term()}, term()) -> pid().
send(Name, Msg) ->
    case whereis_name(Name) of
        undefined ->
            exit({badarg, {Name, Msg}});
        Pid ->
            Pid ! Msg,
            Pid
    end.

%% ---------------------------------------------------------------------------
%% Registration metadata
%% ---------------------------------------------------------------------------
%% Metadata is attached to a registration (keyed by name) and lives exactly as long as
%% the registration does — it is removed automatically when the process exits or is
%% unregistered. A `MetaSpec` is `#{index => #{attr() => value()}, data => term()}`
%% (both optional): `index` is the queryable metadata, `data` an opaque payload returned
%% verbatim. See §4.7 of the design doc.

-if(?DOCATTRS).
-doc """
Registers `Pid` under `{RegistryName, LogicalName}` with metadata, in one fenced step.

`MetaSpec` is `#{index => map(), data => term()}` (both optional; defaults `#{}` and
`undefined`). Like `register_name/2`, returns `yes` on success or `no` if the name is
already taken, no leader is currently elected, or the leader is unreachable — those
are all *adjudicated* verdicts, answered promptly.

A call **timeout** (the member, or the leader behind it, did not answer within
`register_timeout`, §8 — default 5000 ms) **exits** rather than answering `no`: a
timeout means no verdict exists, and masking it as `no` would tell the caller "the
name is taken" when the registration may in fact have committed. Letting the exit
propagate matches what `global`, `syn`, and other registries do — the caller (or its
supervisor) crashes and retries with fresh state. A missing registry (`noproc`) also
exits — a usage error.
""".
-endif.
-spec register_name({atom(), term()}, pid(), map()) -> yes | no.
register_name({RegistryName, LogicalName}, Pid, MetaSpec) ->
    gen_statem:call(
        member_name(RegistryName),
        {register, LogicalName, Pid, meta_of(MetaSpec)},
        dgen_config:register_timeout(#{})
    ).

-if(?DOCATTRS).
-doc """
Replaces the metadata of the existing registration `{RegistryName, LogicalName}`.

`MetaSpec` is `#{index => map(), data => term()}` (both optional; an omitted field
becomes `#{}` / `undefined` — this is a replace, not a merge). Routes through the leader
and rides the fenced commit. Returns `ok`, `{error, not_registered}` if the name is not
currently bound, or `{error, no_leader}` if no leader is elected (or leadership changed
mid-flight — retry).
""".
-endif.
-spec set_metadata({atom(), term()}, map()) -> ok | {error, not_registered | no_leader}.
set_metadata({RegistryName, LogicalName}, MetaSpec) ->
    {Index, Data} = meta_of(MetaSpec),
    try
        gen_statem:call(
            member_name(RegistryName),
            {set_metadata, LogicalName, Index, Data},
            %% Bounded by the same caller-side knob as register_name/2,3 rather than
            %% `gen_server:call/2`'s hidden 5s default: this is a leader-routed write
            %% on the same pipeline, so an operator who tunes how long a write may
            %% block should not find one of them ignoring the setting.
            dgen_config:register_timeout(#{})
        )
    catch
        exit:_ -> {error, no_leader}
    end.

-if(?DOCATTRS).
-doc """
Snapshot read of a registration's metadata — served lock-free from the calling process.

Like `whereis_name/1`, this is an `ets:lookup/2` against the local member's `protected`
table with no member round-trip. Returns `{ok, #{pid := pid(), index := map(), data :=
term()}}` for a registered name, or `undefined` if it is not registered (or the member's
table does not exist yet). May lag a recent change made on another node.
""".
-endif.
-spec get_metadata({atom(), term()}) ->
    {ok, #{pid := pid(), index := map(), data := term()}} | undefined.
get_metadata({RegistryName, LogicalName}) ->
    try ets:lookup(names_table(RegistryName), LogicalName) of
        [{_Name, Pid, Index, Data} | _] -> {ok, #{pid => Pid, index => Index, data => Data}};
        [] -> undefined
    catch
        error:badarg -> undefined
    end.

-if(?DOCATTRS).
-doc """
Consistent metadata read routed through the leader (authoritative, never stale).

Returns the same shape as `get_metadata/1`. More expensive (one network hop) but
reflects the leader's committed view.
""".
-endif.
-spec get_metadata_consistent({atom(), term()}) ->
    {ok, #{pid := pid(), index := map(), data := term()}} | undefined.
get_metadata_consistent({RegistryName, LogicalName}) ->
    try
        gen_statem:call(member_name(RegistryName), {get_metadata, LogicalName})
    catch
        exit:_ -> undefined
    end.

-if(?DOCATTRS).
-doc """
Finds every registration whose indexed metadata satisfies *all* of `Constraints`.

`Constraints` is `#{attr() => value()}` — a conjunction of exact equalities (AND-equal)
matched against each registration's `index` map. Returns a point-in-time list of
`#{name, pid, index, data}` matches (possibly empty), or `{error, empty_query}` if
`Constraints` is empty (use a future `list/1` for "everything").

This is a **batch-consistent snapshot** read of the local member's replica: it runs on
the member's mailbox (unlike the lock-free single-key reads) so it never observes a
half-applied group commit, but it may still lag a change made on another node. A
returned pid may already have died — treat results as candidates, not liveness
guarantees.
""".
-endif.
-spec query(atom(), map()) ->
    [#{name := term(), pid := pid(), index := map(), data := term()}] | {error, empty_query}.
query(_RegistryName, Constraints) when map_size(Constraints) =:= 0 ->
    {error, empty_query};
query(RegistryName, Constraints) ->
    try
        gen_statem:call(member_name(RegistryName), {query, Constraints})
    catch
        exit:_ -> []
    end.

-if(?DOCATTRS).
-doc """
Like `query/2`, but routed through the leader for an authoritative (never-stale) result.

Returns the same shape as `query/2`. More expensive (it serialises on the leader's
mailbox, one network hop from a follower) but reflects the leader's committed view.
""".
-endif.
-spec query_consistent(atom(), map()) ->
    [#{name := term(), pid := pid(), index := map(), data := term()}] | {error, empty_query}.
query_consistent(_RegistryName, Constraints) when map_size(Constraints) =:= 0 ->
    {error, empty_query};
query_consistent(RegistryName, Constraints) ->
    try
        gen_statem:call(member_name(RegistryName), {query_consistent, Constraints})
    catch
        exit:_ -> []
    end.

%% ---------------------------------------------------------------------------
%% Presence: durable watch/notify subscriptions
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Creates (or updates) a **durable** presence subscription `SubId`: keeps the processes
matching the `Notify` query up to date with the set of processes matching the `Watch`
query.

`Watch` and `Notify` are `query/0` values — a `{all, #{attr => value}}` conjunction of
exact equalities over registration `index` metadata (a bare map is accepted and read as
`{all, Map}`). `SubId` is any application term; a subscribe with an existing `SubId` is
an idempotent **upsert** (replaces its queries).

Whenever a committed batch of registrations changes which processes satisfy `Watch` — a
process registers into it, unregisters/dies out of it, or a metadata change moves it in
or out — the registry sends, to **every process currently matching `Notify`**, one
message:

```erlang
{dgen_presence, SubId, Events}
```

where `Events` is a non-empty list of `presence_event/0` — `{joined, Name, Pid}` /
`{left, Name, Pid}`. Every process that matches `Notify` receives an **initial snapshot**
(the current `Watch` set as a batch of `joined` events) when it enters the notify set —
whether that is at subscribe time or when it registers into `Notify` later — and deltas
thereafter. A viewer therefore always has a complete, continuously-maintained view from
the moment it appears, so the subscription can safely be created before any viewer exists
(e.g. tied to a database entity's lifetime).

## Durability

The subscription is stored in the elector's **durable** backend state, not tied to any
Erlang process: it outlives the cluster. An application can therefore tie a
subscription's lifetime to a database entity (subscribe when the entity is created,
`unsubscribe/2` when it is deleted) and have presence come back intact after a
scale-to-zero — the durable subscription is reloaded and re-fed to the leader on
restart, and processes matching `Notify` resume receiving updates as they re-register.

Returns `ok`, or `{error, empty_query}` if either query is empty (validated locally).
The write is sent to the elector as a durable **cast** (fire-and-forget) for low latency,
so `ok` means "accepted for durable processing", not "already committed": it commits
asynchronously and `subscriptions/1` reflects it shortly after. Durability still holds —
the change commits in the elector's backend transaction and survives a full cluster
restart — and because a subscription is an idempotent upsert keyed by `SubId`, a write
lost in the narrow window before the elector durably enqueues it is safely recoverable by
re-subscribing (the application owns the source of truth). A missing registry (`noproc`)
exits.
""".
-endif.
-spec subscribe(atom(), term(), query(), query()) -> ok | {error, empty_query}.
subscribe(RegistryName, SubId, Watch, Notify) ->
    {all, W} = NWatch = normalize_query(Watch),
    {all, N} = NNotify = normalize_query(Notify),
    case map_size(W) =:= 0 orelse map_size(N) =:= 0 of
        true ->
            {error, empty_query};
        false ->
            elector_cast(RegistryName, {subscribe, SubId, NWatch, NNotify})
    end.

-if(?DOCATTRS).
-doc """
Removes the durable presence subscription `SubId` (from `subscribe/4`). Returns `ok`
(idempotent — removing an unknown `SubId` is a no-op). Sent as a durable cast, applied
asynchronously (see `subscribe/4`). A missing registry exits.
""".
-endif.
-spec unsubscribe(atom(), term()) -> ok.
unsubscribe(RegistryName, SubId) ->
    elector_cast(RegistryName, {unsubscribe, SubId}).

-if(?DOCATTRS).
-doc """
Removes **all** durable presence subscriptions from the registry. Returns `ok`.

Like `unsubscribe/2` but wholesale — a durable cast, applied asynchronously, pushed to
the leader so it drops every subscription's live state. Useful for tearing down presence
without deleting the registry itself (a full `delete/2` also removes them, along with
everything else).
""".
-endif.
-spec unsubscribe_all(atom()) -> ok.
unsubscribe_all(RegistryName) ->
    elector_cast(RegistryName, unsubscribe_all).

-if(?DOCATTRS).
-doc """
Returns the registry's durable presence subscriptions as `#{SubId => {Watch, Notify}}`.

A read of the elector's committed state (shared cluster-wide and durable), so it
reflects every subscription regardless of which node created it. Returns `#{}` if the
registry cannot currently be reached.
""".
-endif.
-spec subscriptions(atom()) -> #{term() => {query(), query()}}.
subscriptions(RegistryName) ->
    with_elector(RegistryName, #{}, fun(Pid) ->
        dgen_server:priority_call(Pid, get_subscriptions)
    end).

%% Route a durable subscription write to the elector as a fire-and-forget cast (handled
%% by dgen_registry_elector:handle_cast_tx/3 — enqueued durably and committed in the
%% consume transaction).  A missing registry is a usage error and exits, mirroring the
%% register path; a cast to a live elector that then dies is a harmless no-op.
elector_cast(RegistryName, Msg) ->
    case elector_pid(RegistryName) of
        undefined -> exit({noproc, {?MODULE, elector, RegistryName}});
        Pid -> dgen_server:cast(Pid, Msg)
    end.

%% ---------------------------------------------------------------------------
%% Teardown / durable-state cleanup
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Removes **all** of the registry's durable backend state. Returns `ok`.

Every key a registry writes — the elector's membership/leader/subscription state and its
message queue, plus the leader-fence and version keys — lives under a single tenant
keyspace prefix derived from `Name`, so this clears exactly that registry's keys (and no
other registry sharing the tenant). Use it to reclaim the durable footprint of a
registry you are done with — e.g. one of many short-lived, per-entity registries in a
shared tenant (see the "Process identity" note on why nothing else is left behind).

**Stop the registry first.** `delete/2` operates directly on the backend and assumes no
live processes: a running elector caches its state in memory and would re-write it (and
so re-create the keys) on its next commit. The correct sequence is
`Supervisor.stop(Sup)` (the pid `start_link/2,3` returned), then `delete/2` with the
tenant you started the registry with.

This does not delete anything the registered processes themselves own; it only removes
the registry's own bookkeeping.
""".
-endif.
-spec delete(atom(), dgen_backend:tenant()) -> ok.
delete(Name, Tenant) ->
    Tuid = dgen_registry_elector:tuid(Name),
    Backend = dgen_config:backend(),
    dgen_backend:transactional(Tenant, fun({Tx, Dir}) ->
        {StartKey, EndKey} = Backend:dir_range(Dir, Tuid),
        Backend:clear_range(Tx, StartKey, EndKey)
    end),
    ok.

%% Normalise a public query into the internal tagged form: a bare constraints map is
%% read as `{all, Map}` (AND-equal); an already-tagged query passes through.
-spec normalize_query(query()) -> {'all', map()}.
normalize_query({all, C} = Q) when is_map(C) -> Q;
normalize_query(C) when is_map(C) -> {all, C}.

%% Parse a public MetaSpec (`#{index => …, data => …}`, both optional) into the internal
%% `{Index, Data}` pair, defaulting to the empty metadata.
-spec meta_of(map()) -> {map(), term()}.
meta_of(MetaSpec) ->
    {maps:get(index, MetaSpec, #{}), maps:get(data, MetaSpec, undefined)}.

%% ---------------------------------------------------------------------------
%% Consistent name lookup (leader-routed)
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Consistent read routed through the leader.

Returns the authoritative Pid for `LogicalName`, or `undefined` if not
registered. More expensive than `whereis_name/1` but never stale.
""".
-endif.
-spec whereis_name_consistent({atom(), term()}) -> pid() | undefined.
whereis_name_consistent({RegistryName, LogicalName}) ->
    try
        gen_statem:call(member_name(RegistryName), {whereis, LogicalName})
    catch
        exit:_ -> undefined
    end.

%% ---------------------------------------------------------------------------
%% Convenience queries (bypass durable queue, always fresh)
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Returns the current leader member id, or `undefined` if no leader is elected.".
-endif.
-spec get_leader(Name :: atom()) -> member_id() | undefined.
get_leader(Name) ->
    with_elector(Name, undefined, fun(Pid) -> dgen_server:priority_call(Pid, get_leader) end).

-if(?DOCATTRS).
-doc "Returns the current leader epoch. Increments each time a new leader is elected.".
-endif.
-spec get_epoch(Name :: atom()) -> non_neg_integer().
get_epoch(Name) ->
    with_elector(Name, 0, fun(Pid) -> dgen_server:priority_call(Pid, get_epoch) end).

%% Poll interval and per-probe call bound for await_ready/2.
-define(READY_POLL_INTERVAL, 50).
-define(READY_CALL_TIMEOUT, 1000).

-if(?DOCATTRS).
-doc """
Is the registry on this node ready to serve registrations *right now*?

Returns `true` once the local member both knows a leader and has synced registry
state (applied the leader's snapshot, or assumed leadership itself). Returns `false`
while it is still starting/joining, has no elected leader, or is momentarily
unresponsive (a busy member is treated as not-ready rather than blocking the caller).

This is a point-in-time check; use `await_ready/2` to block until ready. Note that
readiness means registrations are being *served*, not that any particular
registration will return `yes` (a name may already be taken, or leadership may move).
""".
-endif.
-spec ready(Name :: atom()) -> boolean().
ready(Name) ->
    try gen_statem:call(member_name(Name), ready, ?READY_CALL_TIMEOUT) of
        Ready when is_boolean(Ready) -> Ready;
        _ -> false
    catch
        %% Member starting/restarting (noproc), or busy past the probe bound
        %% (timeout) — not ready yet.
        exit:_ -> false
    end.

-if(?DOCATTRS).
-doc """
Reports this node's member's own view of the registry, as a map:

- `member_id` — this member's `member_id/0`.
- `leader` — the member id it currently believes leads, or `undefined`.
- `is_leader` — whether that belief names itself.
- `epoch` — the leadership epoch it has heard (§4.2).
- `synced` — whether it has applied a snapshot or assumed leadership.
- `applied_version` — the commit version its replica has applied up to (§4.5).

This is a member's **belief**, which is deliberately not the same thing as
`get_leader/1`'s committed answer from the elector: a deposed leader that has not
yet heard about the handoff still reports `is_leader => true` here while
`get_leader/1` already names its successor. That gap is the fenced window of §5.1,
and seeing it is the point of this call.

Side-effect free — a plain state read, useful for operational introspection and for
asserting replication invariants across members. Returns `undefined` if the member
is not running.
""".
-endif.
-spec status(Name :: atom()) -> map() | undefined.
status(Name) ->
    try gen_statem:call(member_name(Name), status, ?READY_CALL_TIMEOUT) of
        Status when is_map(Status) -> Status;
        _ -> undefined
    catch
        exit:_ -> undefined
    end.

-if(?DOCATTRS).
-doc "Blocks until `ready/1` holds, or 5s elapses. See `await_ready/2`.".
-endif.
-spec await_ready(Name :: atom()) -> ok | {error, timeout}.
await_ready(Name) ->
    await_ready(Name, 5000).

-if(?DOCATTRS).
-doc """
Blocks until the registry on this node is ready to serve registrations, or `Timeout`
(milliseconds) elapses.

Returns `ok` once `ready/1` holds, or `{error, timeout}` if the deadline passes first.
Intended for a node that has just started/joined a cluster: it waits out leader
election and the join handoff (the leader gathers and delivers the names snapshot)
before the caller starts registering, so registrations are not fast-rejected against a
not-yet-known leader. Safe to call from many nodes; it only reads local member state.
""".
-endif.
-spec await_ready(Name :: atom(), Timeout :: non_neg_integer()) -> ok | {error, timeout}.
await_ready(Name, Timeout) ->
    Deadline = dgen_utils:real_monotonic_ms() + Timeout,
    await_ready_loop(Name, Deadline).

%% The poll sleeps and reads the clock through `dgen_utils`, which the eta
%% transform does not touch, and that is load-bearing: this module carries the
%% transform (see the include at the top), so a bare `timer:sleep/1` here becomes
%% `eta_time:sleep/1` — and under `eta_run` this loop runs in the *driver* while
%% the cluster starts, the one process whose transformed sleep arms a virtual
%% deadline nothing will ever reach (`eta_time:sleep/1`'s own boundary rule).
%% Observed as the whole run wedging in `await_ready_loop` whenever a member was
%% not ready on the very first poll.  Readiness polling is a wall-clock concern:
%% it runs before the schedule owns the system (or on a real node, where there is
%% no schedule at all), exactly like the harness's own `await_quiescent/2`.
await_ready_loop(Name, Deadline) ->
    case ready(Name) of
        true ->
            ok;
        false ->
            case dgen_utils:real_monotonic_ms() < Deadline of
                true ->
                    dgen_utils:real_sleep(?READY_POLL_INTERVAL),
                    await_ready_loop(Name, Deadline);
                false ->
                    {error, timeout}
            end
    end.

-if(?DOCATTRS).
-doc "Returns the list of all current member ids in the registry.".
-endif.
-spec get_members(Name :: atom()) -> [member_id()].
get_members(Name) ->
    with_elector(Name, [], fun(Pid) -> dgen_server:priority_call(Pid, get_members) end).

%% Resolve the elector via `elector_pid/1` and apply `Fun` to it, or return `Default`
%% if the member (and so the elector) cannot currently be found — the registry may not
%% have started yet, or may be mid-restart. Keeps get_leader/get_epoch/get_members
%% bypassing the member's mailbox entirely, as before (§8): only an elector lookup is
%% added, not a member round-trip.
with_elector(Name, Default, Fun) ->
    case elector_pid(Name) of
        undefined -> Default;
        Pid -> Fun(Pid)
    end.

%% ---------------------------------------------------------------------------
%% Process identity helpers
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc """
Returns the registered name of the member process for the given registry name.

Identity today (`member_name(Name) =:= Name`) — the member is registered under
`Name` directly. Kept as a function (rather than inlining `Name` at call sites) so
callers do not depend on that being the case.
""".
-endif.
-spec member_name(atom()) -> atom().
member_name(Name) ->
    Name.

-if(?DOCATTRS).
-doc """
Returns the ETS table name holding the registry's local `Name => Pid` replica.

Identity today (`names_table(Name) =:= Name`) — the member's names table is
named `Name` directly (ETS `named_table` names and Erlang process-registration
names are separate namespaces, so this does not collide with the member's own
registration). The table is owned and written by the member (a `protected`,
`read_concurrency` table) and read lock-free from any process — see
`whereis_name/1`.
""".
-endif.
-spec names_table(atom()) -> atom().
names_table(Name) ->
    Name.

-if(?DOCATTRS).
-doc """
Returns the current elector `pid()` for registry `Name`, or `undefined` if the
member (and so the elector) cannot currently be found.

The elector has no registered name — it is discovered by locating the member
(registered as `Name`), reading its `$ancestors` process-dictionary entry (set by
`proc_lib` at spawn time) to find the shared supervisor, then reading that
supervisor's children (`supervisor:which_children/1`) for the one with child id
`elector`. This is an all-local, in-memory operation (no network hop); it is what
`get_leader/1`, `get_epoch/1`, and `get_members/1` use internally, and is exported
for introspection.
""".
-endif.
-spec elector_pid(atom()) -> pid() | undefined.
elector_pid(Name) ->
    case whereis(Name) of
        undefined ->
            undefined;
        MemberPid ->
            case ancestors_of(MemberPid) of
                [Sup | _] ->
                    case lists:keyfind(elector, 1, supervisor:which_children(Sup)) of
                        {elector, ElectorPid, _Type, _Modules} when is_pid(ElectorPid) ->
                            ElectorPid;
                        _ ->
                            undefined
                    end;
                [] ->
                    undefined
            end
    end.

%% Reads Pid's `$ancestors` process-dictionary entry: the list of supervisor/starter
%% identifiers `proc_lib` records for a process at spawn time, immediate parent
%% first. There is no public `proc_lib` accessor for this (it is conventionally read
%% straight out of the dictionary — the same technique tools like `recon` use); each
%% entry is a pid, or a registered name if that ancestor had one, either of which
%% `supervisor:which_children/1` accepts directly.
-spec ancestors_of(pid()) -> [pid() | atom()].
ancestors_of(Pid) ->
    case erlang:process_info(Pid, dictionary) of
        {dictionary, Dict} -> proplists:get_value('$ancestors', Dict, []);
        undefined -> []
    end.

%% ---------------------------------------------------------------------------
%% Supervisor callbacks
%% ---------------------------------------------------------------------------

init({Name, Tenant, Opts}) ->
    %% Elector must start first: the member discovers it (via this supervisor,
    %% see dgen_registry_member's `discover_elector` handle_continue) and casts
    %% `{join, MemberId}` to it right after. A large consume_k is chosen because the
    %% in-transaction work is very small, and we want to keep a single node as the
    %% sole consumer as much as possible, to avoid leadership churn. consume_k > 1
    %% also disables dgen_server inlining, so every elector call rides the batched
    %% consume loop rather than being served ad hoc on the receiving node — keeping
    %% the consumer (hence the leader) stable.
    %%
    %% The elector is deliberately unnamed (`dgen_server:start_link/3`, no `Reg`):
    %% it has no registered name at all, local or otherwise. The member finds it by
    %% pid via this supervisor instead — see the "Process identity" moduledoc note.
    %% `Name` is this member's identity; `Keyspace` is the durable prefix every
    %% member of the registry coordinates through.  They are the same atom in the
    %% ordinary one-member-per-node case; `keyspace` splits them so several members
    %% of one registry can share a VM (see start_link/3's docs).
    Keyspace = maps:get(keyspace, Opts, Name),
    ElectorSpec = #{
        id => elector,
        start =>
            {dgen_server, start_link, [
                dgen_registry_elector,
                #{name => Name, keyspace => Keyspace},
                [{tenant, Tenant}, {consume_k, 50}]
            ]},
        restart => permanent,
        shutdown => 5000,
        type => worker,
        modules => [dgen_server, dgen_registry_elector]
    },

    %% Tuid matches the elector's (both derive it from dgen_registry_elector:tuid/1)
    %% so the member can compute the leader key and the per-registry version key
    %% directly, against the same keyspace the elector's fence writes.  Derived from
    %% `Keyspace`, not `Name`: every member of a registry must fence against the same
    %% leader key even when their identities differ.
    Tuid = dgen_registry_elector:tuid(Keyspace),
    MemberSpec = #{
        id => member,
        start =>
            {dgen_registry_member, start_link, [
                Name,
                #{
                    name => Name,
                    tenant => Tenant,
                    tuid => Tuid,
                    config => Opts
                }
            ]},
        restart => permanent,
        shutdown => 5000,
        type => worker,
        modules => [dgen_registry_member]
    },

    %% The connector keeps Erlang distribution in step with the DB-backed membership
    %% (the proactive mesh, the backstop reap, the leader-liveness probe) — the
    %% node-level connectivity plumbing, split out of the member so each has one job.
    %% It is unnamed and holds only the elector pid; it is started **after** the member
    %% so it can discover the elector by walking from the (already-registered) member,
    %% exactly as the member does. `Opts` is threaded through so the connector can
    %% resolve its `connectivity` mode (§8) — `provided_externally` turns off the
    %% proactive mesh. See dgen_registry_connector.
    ConnectorSpec = #{
        id => connector,
        start =>
            {dgen_registry_connector, start_link, [
                Name,
                #{name => Name, config => Opts}
            ]},
        restart => permanent,
        shutdown => 5000,
        type => worker,
        modules => [dgen_registry_connector]
    },

    %% one_for_all: the elector, member, and connector are one unit — the member and
    %% connector each hold a pid reference to the elector, discovered once at startup
    %% (see the moduledoc's "Process identity" note). If any crashes, restart all
    %% together so neither runs with a stale elector reference; there is no
    %% cross-restart pid-staleness case to handle at the application level.  Order
    %% matters: elector first (both others discover it), then member (registers its
    %% name), then connector (walks from the member to the elector).
    {ok,
        {maps:merge(#{strategy => one_for_all, intensity => 5, period => 10}, ?SUP_SIM_FLAGS), [
            ElectorSpec, MemberSpec, ConnectorSpec
        ]}}.
