-module(dgen_registry_elector).
-behaviour(dgen_server).

-define(DOCATTRS, ?OTP_RELEASE >= 27).
-define(SnapshotTimeout, 2000).

-if(?DOCATTRS).
-moduledoc """
`dgen_server` callback module that tracks registry membership and elects a leader.

The elector's state (member map + current leader) is stored durably in the
backend and is shared across every node that runs the same named registry.
Messages arrive via a durable FIFO queue, so membership changes are processed
one at a time, serialised through the backend.

## Leader election

The incumbent leader is kept as long as it remains a member — leadership
only changes when the incumbent leaves or no leader has been elected yet.
This prevents thrashing when a non-leader node happens to win a backend
transaction race.

When a new leader must be chosen (no valid incumbent), the node that wins
the backend transaction race is preferred: if `{node(), MemberName}` is a
current member, that node becomes leader. If not (transient window during
startup), `lists:min/1` over live member IDs is used as a deterministic
fallback.

## Replication on leadership change

When `elect_leader/4` returns a leader different from the previous one,
`handle_cast_tx` returns `{lock, NewState}`, triggering the following
sequence before the lock clears:

1. **Commit + lock** — the backend transaction commits the new member set
   and leader key atomically, then sets a distributed lock key that pauses
   all other elector consumers on all nodes.  The lock is held for at most
   `?SnapshotTimeout × 2` ms — the worst-case duration of two synchronous
   cross-node calls in `handle_locked/4`.  An Erlang `after` block
   guarantees the lock is cleared even if `handle_locked` raises; only a
   hard process kill (SIGKILL / VM abort) can leave it permanently set.
2. **Snapshot acquisition** — `handle_locked/4` decides what names snapshot
   the new leader starts with:
   - If the new leader is a brand-new member with no prior follower state
     (only possible when there is no valid incumbent, i.e. first join into
     an existing cluster), the elector calls the old leader via
     `{transfer_snapshot}`. The old leader flushes any pending registrations
     from its mailbox, returns its authoritative names list, and sets its
     own leader field to `undefined` — relinquishing leadership atomically
     in a single gen_server call.
   - Otherwise (an existing member takes over, or leader died and a follower
     is promoted), the new leader uses `self_snapshot` — its own in-memory
     names map, which is already a follower replica.

3. **Leader assumption** — the elector calls the new leader via
   `{elector_assume_and_distribute, Snapshot, MemberId, AllIds, Tokens, Epoch}`.
   The new leader stores the epoch, applies the snapshot, sets up
   `erlang:monitor/2` for every registered pid, and casts
   `{apply_names_snapshot, ..., Epoch}` to every follower from its own process.

4. **Follower sync** — each follower receives `{apply_names_snapshot}`,
   overwrites its names map, and updates its leader field. Because these
   casts originate from the same process as subsequent `{name_registered}`
   broadcasts, Erlang's per-pair FIFO guarantee ensures every follower
   sees the snapshot before any registration that post-dates the transition.

5. **Lock clears** — `handle_locked` returns, the lock key is cleared, and
   all waiting consumers resume.

## Leader key in the backend

```
Key path: {Tuid, <<"leader">>}
Value:    term_to_binary(MemberId | undefined)
```
""".
-endif.

-export([
    init/1,
    handle_cast_tx/3,
    handle_call/3,
    handle_locked/4,
    leader_db_key/2
]).

-export_type([member_id/0, member_info/0, registry_state/0]).

-type member_id() :: {node(), atom()}.
-type member_info() :: #{joined_at := integer(), join_token := reference()}.
-type registry_state() :: #{
    name := atom(),
    members := #{member_id() => member_info()},
    leader := member_id() | undefined,
    epoch := non_neg_integer()
}.

%% ---------------------------------------------------------------------------
%% dgen_server callbacks
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Initialises the elector state with an empty member map and undefined leader.".
-endif.
-spec init(#{name := atom()}) -> {ok, dgen_server:tuid(), registry_state()}.
init(#{name := Name}) ->
    Tuid = {<<"dgen_registry.">>, atom_to_binary(Name)},
    State = #{name => Name, members => #{}, leader => undefined, epoch => 0},
    {ok, Tuid, State}.

-if(?DOCATTRS).
-doc """
Processes membership change messages within a backend transaction.

Handles `{join, MemberId, Token}` and `{member_down, MemberId, Token}`. Returns
`{lock, NewState}` when leadership changes, `{noreply, NewState}` otherwise.

Each `{join}` carries a unique token (a `reference()` generated by the member
process before enqueuing).  The elector stores this token in `member_info`.

A `{member_down, MemberId, Token}` is silently discarded when its token does not
match the stored token for that member — this means the member has rejoined with
a new token since the DOWN was detected, so the message is stale.  This prevents
a partition-recovery race where a `{member_down}` enqueued during the disconnect
is processed after the subsequent `{join}` that heals the cluster.
""".
-endif.
-spec handle_cast_tx(dgen_server:tx_ctx(), term(), registry_state()) ->
    dgen_server:noreply_ret() | dgen_server:lock_ret().

handle_cast_tx(TxCtx, {join, MemberId, Token}, State) ->
    #{name := Name, members := Members, leader := OldLeader, epoch := OldEpoch} = State,
    MemberInfo = #{joined_at => erlang:system_time(millisecond), join_token => Token},
    NewMembers = Members#{MemberId => MemberInfo},
    {NewLeader, NewEpoch} = elect_leader(TxCtx, Name, NewMembers, OldLeader, OldEpoch),
    NewState = State#{members => NewMembers, leader => NewLeader, epoch => NewEpoch},
    if
        NewLeader =/= OldLeader ->
            %% Leadership changed — lock so handle_locked can set up replication paths.
            {lock, NewState};
        true ->
            %% Leader unchanged — route through the leader so all follower messages
            %% come from the same sender (FIFO with subsequent name broadcasts).
            Actions = [
                fun(#{members := All, leader := L, epoch := Epoch}) ->
                    call_to_member(
                        L,
                        {elector_assume_and_distribute, self_snapshot, MemberId, maps:keys(All),
                            member_tokens(All), Epoch}
                    )
                end
            ],
            {noreply, NewState, Actions}
    end;
handle_cast_tx(TxCtx, {member_down, MemberId, Token}, State) ->
    #{name := Name, members := Members, leader := OldLeader, epoch := OldEpoch} = State,
    case maps:get(MemberId, Members, undefined) of
        undefined ->
            %% Already removed — idempotent.
            {noreply, State};
        #{join_token := StoredToken} when StoredToken =/= Token ->
            %% Stale: member rejoined with a new token since this DOWN was detected.
            {noreply, State};
        _ ->
            NewMembers = maps:remove(MemberId, Members),
            {NewLeader, NewEpoch} = elect_leader(TxCtx, Name, NewMembers, OldLeader, OldEpoch),
            NewState = State#{members => NewMembers, leader => NewLeader, epoch => NewEpoch},
            if
                NewLeader =/= OldLeader ->
                    %% Leadership changed — lock to set up new replication paths.
                    {lock, NewState};
                true ->
                    %% Leader unchanged — each surviving member detected the death
                    %% via its own erlang:monitor DOWN signal; no broadcast needed.
                    {noreply, NewState}
            end
    end.

%% ---------------------------------------------------------------------------
%% handle_call/3  (read-only priority_calls — bypasses queue and locks)
%% ---------------------------------------------------------------------------

-if(?DOCATTRS).
-doc "Handles read-only priority calls: `get_leader` and `get_members`.".
-endif.
-spec handle_call(term(), dgen_server:from(), registry_state()) ->
    dgen_server:reply_ret().

handle_call(get_leader, _From, State) ->
    {reply, maps:get(leader, State, undefined), State};
handle_call(get_members, _From, State) ->
    {reply, maps:keys(maps:get(members, State, #{})), State};
handle_call(get_epoch, _From, State) ->
    {reply, maps:get(epoch, State, 0), State}.

-if(?DOCATTRS).
-doc """
Executes the replication sequence after a leadership change, before the lock clears.

See the module doc for the full step-by-step sequence.

`transfer_snapshot` is called only when the new leader is a brand-new member
with no prior follower state — i.e., `Leader =:= MemberId` (the joiner itself
won) and at least one other member existed before it joined. With sticky
leadership this only occurs when there is no valid incumbent (first join into
an existing cluster). In all other cases `self_snapshot` is used.

All calls to member processes are wrapped in `try/catch`. If a target is
unreachable:

- `transfer_snapshot` failure: falls back to `self_snapshot`. The new leader
  starts with a potentially stale names map for that transition window.
- `elector_assume_and_distribute` failure: the lock clears normally. The
  membership change is already committed to the backend; affected members
  self-correct on the next membership event.
""".
-endif.
-spec handle_locked(dgen_server:db_ctx(), dgen_server:event_type(), term(), registry_state()) ->
    dgen_server:noreply_ret().

handle_locked(_DbCtx, cast, {join, MemberId, _Token}, State) ->
    #{members := Members, leader := Leader, epoch := Epoch} = State,
    AllIds = maps:keys(Members),
    Tokens = member_tokens(Members),
    ExistingIds = maps:keys(maps:remove(MemberId, Members)),
    Snapshot =
        if
            Leader =:= MemberId, ExistingIds =/= [] ->
                %% New member won the election but has no prior state.  Call the
                %% old leader to atomically hand off its snapshot and relinquish —
                %% any registration in its mailbox is flushed into the snapshot
                %% before leadership transfers.
                [SnapshotSource | _] = ExistingIds,
                try
                    call_to_member(SnapshotSource, {transfer_snapshot, Leader})
                catch
                    exit:_ -> self_snapshot
                end;
            true ->
                %% Existing member is (or remains) the leader — use its own names.
                self_snapshot
        end,
    try
        call_to_member(
            Leader,
            {elector_assume_and_distribute, Snapshot, MemberId, AllIds, Tokens, Epoch}
        )
    catch
        exit:_ -> ok
    end,
    {noreply, State};
handle_locked(_DbCtx, cast, {member_down, _MemberId, _Token}, State) ->
    #{members := Members, leader := Leader, epoch := Epoch} = State,
    AllIds = maps:keys(Members),
    Tokens = member_tokens(Members),
    case Leader of
        undefined ->
            ok;
        _ ->
            try
                call_to_member(
                    Leader,
                    {elector_assume_and_distribute, self_snapshot, undefined, AllIds, Tokens, Epoch}
                )
            catch
                exit:_ -> ok
            end
    end,
    {noreply, State}.

%% ---------------------------------------------------------------------------
%% Internal helpers
%% ---------------------------------------------------------------------------

%% Prefer the incumbent leader if it is still a member (sticky leadership).
%% This prevents thrashing when a non-leader node wins a queue transaction.
%% Falls back to the local node, then lists:min/1, when the incumbent is gone.
%% Returns {Leader, Epoch}. Epoch increments only when a new leader is chosen.
-spec elect_leader(
    dgen_server:tx_ctx(),
    atom(),
    #{member_id() => member_info()},
    member_id() | undefined,
    non_neg_integer()
) -> {member_id() | undefined, non_neg_integer()}.
elect_leader(#{td := {Tx, Dir}, tuid := Tuid}, Name, Members, OldLeader, OldEpoch) ->
    case OldLeader =/= undefined andalso maps:is_key(OldLeader, Members) of
        true ->
            B = dgen_config:backend(),
            B:set(Tx, B:dir_pack(Dir, leader_key_tuple(Tuid)), term_to_binary(OldLeader)),
            {OldLeader, OldEpoch};
        false ->
            LocalId = {node(), dgen_registry:member_name(Name)},
            Leader =
                case maps:is_key(LocalId, Members) of
                    true ->
                        LocalId;
                    false ->
                        case maps:keys(Members) of
                            [] -> undefined;
                            Ids -> lists:min(Ids)
                        end
                end,
            B = dgen_config:backend(),
            B:set(Tx, B:dir_pack(Dir, leader_key_tuple(Tuid)), term_to_binary(Leader)),
            {Leader, OldEpoch + 1}
    end.

-if(?DOCATTRS).
-doc """
Returns the packed backend key for the leader value.

Exported so callers can set up a backend watch without going through the
elector process.
""".
-endif.
-spec leader_db_key(dgen_backend:dir(), dgen_server:tuid()) -> dgen_backend:key().
leader_db_key(Dir, Tuid) ->
    B = dgen_config:backend(),
    B:dir_pack(Dir, leader_key_tuple(Tuid)).

leader_key_tuple(Tuid) ->
    dgen_key:extend(Tuid, <<"leader">>).

%% Extract {MemberId => Token} from the members map for passing to member processes.
member_tokens(Members) ->
    maps:map(fun(_, #{join_token := T}) -> T end, Members).

call_to_member({Node, Name}, Msg) ->
    %% Guard against automatic distribution reconnect: if the target node is
    %% not currently connected, exit immediately rather than letting
    %% gen_server:call trigger a reconnect.  An unintended reconnect during
    %% handle_locked fires {nodeup} on both sides, causing the peer to re-join
    %% with a new token — the old {member_down} is then discarded as stale and
    %% the partition is never detected.
    case Node =:= node() orelse lists:member(Node, nodes()) of
        true -> gen_server:call({Name, Node}, Msg, ?SnapshotTimeout);
        false -> exit({nodedown, Node})
    end.
